import { useTheme } from "next-themes";
import Head from "next/head";
import MainSection from "/components/MainSection";

const Index = () => {
  return (
    <div>
      <Head>
        <title>Next Themes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <div className="bg-white dark:bg-gray-900">
        <MainSection />
      </div>
    </div>
  );
};

export default Index;
